/* Autogenerated. RP2040 blob mailbox config. */
#pragma once
#define BLOB_MAILBOX_ADDR 0x20040000u
#define BLOB_MAILBOX_MAX 512u
// Region: [BLOB_MAILBOX_ADDR .. BLOB_MAILBOX_ADDR + BLOB_MAILBOX_MAX - 1]